db:
    image: mongo
    ports:
        - "27017:27017"
    expose:
        - "27017"
    volumes:
        - ./data/db:/data/db
        - ./data/configdb:/data/configdb

app:
    build: .
    links:
        - db
    volumes:
        - ./server:/app/server
        - ./server/public:/app/server/public
    ports:
        - "3700:3700"
    environment:
        NODE_ENV: development
        PMSIPLAN_MONGO_URL: mongodb://db:27017/pmsiplan
        PMSIPLAN_API_PREFIX: api
        PMSIPLAN_HISTORY: histo
        PMSIPLAN_LDAP_URL:
        PMSIPLAN_LDAP_SEARCH_BASE:
        PMSIPLAN_LDAP_SEARCH_FILTER:
        PMSIPLAN_LDAP_ADMIN_DN:
        PMSIPLAN_LDAP_ADMIN_PWD:
